
language: node_js

node_js:
  - "stable"
  - "14"
  - "12"
  - "10"

script:
  - npm run lint
  - >
    nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;
    if [ $nodeVersionMajor -ge 12 ]; then
      npm test;
    else
      npm run testWithoutESModules;
    fi;

    if [ $nodeVersionMajor -eq 14 ]; then
      npm run makeCodeCoverageSummaryReport;
      npm run makeCodeCoverageDetailReport;
      coveralls < coverage/lcov.info;
    else
      echo "*** Do not make coverage reports for non node.js 14 builds ($nodeVersionMajor)";
    fi;
